# HLint configuration file
# https://github.com/ndmitchell/hlint
##########################

- ignore: {name: "Eta reduce"}
- ignore: {name: "Avoid lambda"}
- ignore: {name: "Use zipWith"}
- ignore: {name: "Use tuple-section"}
- ignore: {name: "Redundant map", within: "NITTA.Model.ProcessorUnits.Fram"}
- ignore: {name: "Redundant map", within: "NITTA.Model.ProcessorUnits.Fram"}
- ignore: {name: "Use camelCase", within: "NITTA.Intermediate.Value.Tests"}
- ignore: {name: "Evaluate", within: "NITTA.Intermediate.Value.Tests"}
- ignore: {name: "Use <$>", within: "NITTA.UIBackend.ViewHelper"}
- ignore: {name: "Avoid lambda using `infix`", within: "NITTA.Project.Template"}
- ignore: {name: "Reduce duplication", within: "NITTA.Model.Tests.Microarchitecture"}
- ignore: {name: "Reduce duplication", within: "NITTA.Model.ProcessorUnits.Multiplier.Tests"}
- ignore: {name: "Reduce duplication", within: "NITTA.Model.ProcessorUnits.Divider.Tests"}
- ignore: {name: "Reduce duplication", within: "NITTA.Model.ProcessorUnits.Tests.DSL.Tests"}
