# HLint configuration file
# https://github.com/ndmitchell/hlint
##########################

- ignore: {name: "Eta reduce"}
- ignore: {name: "Avoid lambda"}
- ignore: {name: "Use zipWith"}
- ignore: {name: "Use tuple-section"}
- ignore: {name: "Redundant map", within: "NITTA.Model.ProcessorUnits.Fram"}
- ignore: {name: "Redundant map", within: "NITTA.Model.ProcessorUnits.Fram"}
- ignore: {name: "Use camelCase", within: "NITTA.Intermediate.Value.Tests"}
- ignore: {name: "Evaluate", within: "NITTA.Intermediate.Value.Tests"}
- ignore: {name: "Use <$>", within: "NITTA.UIBackend.ViewHelper"}

- arguments:
    - -XQuasiQuotes
    - -XDeriveGeneric
    - -XFunctionalDependencies
    - -XLambdaCase
    - -XNamedFieldPuns
    - -XScopedTypeVariables
