# HLint configuration file
# https://github.com/ndmitchell/hlint
##########################

# Force NITTA.Utils.Base

- warn: {lhs: "Data.Set.unions (map f l)", rhs: NITTA.Utils.Base.unionsMap x}
- warn: {lhs: "head (Data.Set.elems s)", rhs: NITTA.Utils.Base.oneOf s}

- warn: {lhs: "Data.Text.pack (Data.String.ToString.toString s)", rhs: NITTA.Utils.Base.toText s}
- warn: {lhs: "Data.Text.pack (show s)", rhs: NITTA.Utils.Base.showText s}
# - warn: {lhs: "fromString (Data.Text.unpack x)", rhs: fromText x}
- warn: {lhs: "read (Data.Text.unpack t)", rhs: NITTA.Utils.Base.readText t}

# Ignore:

- ignore: {name: "Eta reduce"}
- ignore: {name: "Avoid lambda"}
- ignore: {name: "Use zipWith"}
- ignore: {name: "Use tuple-section"}
- ignore: {name: "Redundant map", within: "NITTA.Model.ProcessorUnits.Fram"}
- ignore: {name: "Use camelCase", within: "NITTA.Intermediate.Value.Tests"}
- ignore: {name: "Evaluate", within: "NITTA.Intermediate.Value.Tests"}
- ignore: {name: "Use <$>", within: "NITTA.UIBackend.ViewHelper"}
- ignore: {name: "Avoid lambda using `infix`", within: "NITTA.Project.Template"}
- ignore: {name: "Reduce duplication", within: "NITTA.Model.Tests.Microarchitecture"}
- ignore: {name: "Use list comprehension", within: "Spec"}

- ignore: {name: "Reduce duplication", within: "NITTA.Model.ProcessorUnits.Multiplier.Tests"}
- ignore: {name: "Reduce duplication", within: "NITTA.Model.ProcessorUnits.Divider.Tests"}
- ignore: {name: "Reduce duplication", within: "NITTA.Model.ProcessorUnits.Tests.DSL.Tests"}
- ignore: {name: "Reduce duplication", within: "NITTA.Utils.Tests" }
- ignore: {name: "Reduce duplication", within: "NITTA.Tests" }
- ignore: {name: "Reduce duplication", within: "NITTA.Model.ProcessorUnits.Accum.Tests" }
