#2/* Load */ oe <= 1; wr <= 0; addr <= 0;
#2/* Load */ oe <= 1; wr <= 0; addr <= 0;
#2/* Nop  */ oe <= 0; wr <= 0; addr <= 0;
#2/* Save */ oe <= 0; wr <= 1; addr <= 1; value_i <= 42;
#2/* Save */ oe <= 0; wr <= 1; addr <= 1; value_i <= 42;
#2/* Nop  */ oe <= 0; wr <= 0; addr <= 0;
#2/* Nop  */ oe <= 0; wr <= 0; addr <= 0;
#2/* Save */ oe <= 0; wr <= 1; addr <= 0; value_i <= 42;
#2/* Save */ oe <= 0; wr <= 1; addr <= 0; value_i <= 42;
#2/* Nop  */ oe <= 0; wr <= 0; addr <= 0;
#2/* Nop  */ oe <= 0; wr <= 0; addr <= 0;
#2/* Nop  */ oe <= 0; wr <= 0; addr <= 0;
#2/* Load */ oe <= 1; wr <= 0; addr <= 1;
#2/* Load */ oe <= 1; wr <= 0; addr <= 1;
#2/* Nop  */ oe <= 0; wr <= 0; addr <= 0;
#2/* Nop  */ oe <= 0; wr <= 0; addr <= 0;
#2/* Nop  */ oe <= 0; wr <= 0; addr <= 0;
#2/* Save */ oe <= 0; wr <= 1; addr <= 0; value_i <= 42;
#2/* Save */ oe <= 0; wr <= 1; addr <= 0; value_i <= 42;
#2/* Nop  */ oe <= 0; wr <= 0; addr <= 0;
#2/* Nop  */ oe <= 0; wr <= 0; addr <= 0;
#2/* Nop  */ oe <= 0; wr <= 0; addr <= 0;
#2/* Load */ oe <= 1; wr <= 0; addr <= 1;
#2/* Load */ oe <= 1; wr <= 0; addr <= 1;
#2/* Nop  */ oe <= 0; wr <= 0; addr <= 0;
#2/* Nop  */ oe <= 0; wr <= 0; addr <= 0;
#2/* Nop  */ oe <= 0; wr <= 0; addr <= 0;
#2/* Load */ oe <= 1; wr <= 0; addr <= 0;
#2/* Load */ oe <= 1; wr <= 0; addr <= 0;
#2/* Nop  */ oe <= 0; wr <= 0; addr <= 0;
#2/* Nop  */ oe <= 0; wr <= 0; addr <= 0;
#2/* Nop  */ oe <= 0; wr <= 0; addr <= 0;
