name: Haskell Sanity

on:
  pull_request:

jobs:

  hlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: 'Set up HLint'
      uses: haskell/actions/hlint-setup@v1
      with:
        version: '3.1.6'

    - name: 'Run HLint'
      uses: haskell/actions/hlint-run@v1
      with:
        path: .
        fail-on: warning

  fourmolu:
    runs-on: ubuntu-latest
    steps:
      - name: Install fourmolu
        run: |
          mkdir -p "$HOME/.local/bin"
          wget -qO "$HOME/.local/bin/fourmolu" "https://github.com/fourmolu/fourmolu/releases/download/v0.7.0.1/fourmolu-0.7.0.1-linux-x86_64"
          chmod +x "$HOME/.local/bin/fourmolu"
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - uses: actions/checkout@v2
      - name: Check formatting
        run: find . -name '*.hs' | xargs fourmolu -m check
